### ISSUE TITLE
CloudWatch Formatter does not format the dimension correct

### ISSUE THREAD

**Issue by Jannnnnn** [stechstudio/laravel-metrics#8]
### Used library version

```bash
docker-compose exec worker composer show stechstudio/laravel-metrics
name     : stechstudio/laravel-metrics
descrip. : Easily track metrics from Laravel events, or on your own
keywords : 
versions : * 1.2
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : 
source   : [git] https://github.com/stechstudio/laravel-metrics.git 506593d1ddbb42fbfd972959fc3414a46c6106b8
dist     : [zip] https://api.github.com/repos/stechstudio/laravel-metrics/zipball/506593d1ddbb42fbfd972959fc3414a46c6106b8 506593d1ddbb42fbfd972959fc3414a46c6106b8
path     : /var/www/html/vendor/stechstudio/laravel-metrics
names    : stechstudio/laravel-metrics

support
issues : https://github.com/stechstudio/laravel-metrics/issues
source : https://github.com/stechstudio/laravel-metrics/tree/1.2

autoload
psr-4
STS\Metrics\ => src

requires
illuminate/support ^5.0|^6.0|^7.0
influxdb/influxdb-php ^1.14

requires (dev)
aws/aws-sdk-php ^3.133
mockery/mockery ^1.0
orchestra/testbench ~5.0
phpunit/phpunit ^9.0
```

### Step to reproduce 

```bash 
php artisan tinker
```

```php
$metric = (new \STS\Metrics\Metric("file_uploaded"))
     ->setResolution(1)
     ->setValue(50)
     ->setUnit('Megabytes')
     ->setTags(['user' => 54]);

dd(
    app(STS\Metrics\Drivers\CloudWatch::class)->format($metric)
);
```

### Result of the dd

```php
[
     "MetricName" => "file_uploaded",
     "Dimensions" => [
          "user" => 54,
     ],
     "StorageResolution" => 1,
     "Timestamp" => 1599226806,
     "Unit" => "Megabytes",
     "Value" => 50,
]
```

### Expected

See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_Dimension.html

```php
[
     "MetricName" => "file_uploaded",
     "Dimensions" => [
           [
               "Name" => "user",
               "Value" => 54,
          ],
     ],
     "StorageResolution" => 1,
     "Timestamp" => 1599226806,
     "Unit" => "Megabytes",
     "Value" => 50,
]
```

### Stack Trace

```bash
[04-Sep-2020 13:47:17 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: Found 1 error while validating the input provided for the PutMetricData operation:
app_1            | [MetricData][0][Dimensions][user] must be an associative array. Found int(54) in /var/www/html/vendor/aws/aws-sdk-php/src/Api/Validator.php:65
app_1            | Stack trace:
app_1            | #0 /var/www/html/vendor/aws/aws-sdk-php/src/Middleware.php(78): Aws\Api\Validator->validate('PutMetricData', Object(Aws\Api\StructureShape), Array)
app_1            | #1 /var/www/html/vendor/aws/aws-sdk-php/src/IdempotencyTokenMiddleware.php(77): Aws\Middleware::Aws\{closure}(Object(Aws\Command), NULL)
app_1            | #2 /var/www/html/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(64): Aws\IdempotencyTokenMiddleware->__invoke(Object(Aws\Command))
app_1            | #3 /var/www/html/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): Aws\AwsClient->executeAsync(Object(Aws\Command))
app_1            | #4 /var/www/html/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(86): Aws\AwsClient->execute(Object(Aws\Command))
app_1            | #5 /var/www/html/vendor/stechstudio/laravel-metrics/src/Drivers/CloudWatch.php(82): Aws\AwsClient->__call( in /var/www/html/vendor/aws/aws-sdk-php/src/Api/Validator.php on line 65
```

### Used AWS SDK

```bash
composer show aws/aws-sdk-php
name     : aws/aws-sdk-php
descrip. : AWS SDK for PHP - Use Amazon Web Services in your PHP project
keywords : amazon, aws, cloud, dynamodb, ec2, glacier, s3, sdk
versions : * 3.148.1
type     : library
license  : Apache License 2.0 (Apache-2.0) (OSI approved) https://spdx.org/licenses/Apache-2.0.html#licenseText
homepage : http://aws.amazon.com/sdkforphp
source   : [git] https://github.com/aws/aws-sdk-php.git 56caf889ddc8dcc5b6999c234998f3b945d787e3
dist     : [zip] https://api.github.com/repos/aws/aws-sdk-php/zipball/56caf889ddc8dcc5b6999c234998f3b945d787e3 56caf889ddc8dcc5b6999c234998f3b945d787e3
path     : /var/www/html/vendor/aws/aws-sdk-php
names    : aws/aws-sdk-php

autoload
psr-4
Aws\ => src/
files

requires
ext-json *
ext-pcre *
ext-simplexml *
guzzlehttp/guzzle ^5.3.3|^6.2.1|^7.0
guzzlehttp/promises ^1.0
guzzlehttp/psr7 ^1.4.1
mtdowling/jmespath.php ^2.5
php >=5.5

requires (dev)
andrewsville/php-token-reflection ^1.4
aws/aws-php-sns-message-validator ~1.0
behat/behat ~3.0
doctrine/cache ~1.4
ext-dom *
ext-openssl *
ext-pcntl *
ext-sockets *
nette/neon ^2.3
paragonie/random_compat >= 2
phpunit/phpunit ^4.8.35|^5.4.3
psr/cache ^1.0
psr/simple-cache ^1.0
sebastian/comparator ^1.2.3

suggests
aws/aws-php-sns-message-validator To validate incoming SNS notifications
doctrine/cache To use the DoctrineCacheAdapter
ext-curl To send requests using cURL
ext-openssl Allows working with CloudFront private distributions and verifying received SNS messages
ext-sockets To use client-side monitoring
```

**Comment by Jannnnnn** [comment]
@jszobody thanks for the fast fix! 
Maybe you tagged a wrong version? https://github.com/stechstudio/laravel-metrics/releases/tag/1.2.1

**Comment by jszobody** [comment]
🤦

**Comment by Jannnnnn** [comment]
Yeah, works :+1:
